# ソースのビルド用コンテナ
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu AS builder

# sdkman!からgradleを入手→パスを通す
RUN apt-get update
RUN apt-get -y install curl
RUN apt-get -y install zip
RUN curl -s "https://get.sdkman.io" | bash
RUN echo ". $HOME/.sdkman/bin/sdkman-init.sh; sdk install gradle" | bash

# ソースを全て/app配下に持っていく
WORKDIR /app
# RUN mkdir sample-api
COPY ./backend/sample-api/ /app/

EXPOSE 8080

# RUN cd sample-api
# gradle build
# RUN $HOME/.sdkman/candidates/gradle/current/bin/gradle build

RUN ./gradlew clean build

RUN ./gradlew tasks

# CMD ["java", "-jar", "build/lib/sample-api-0.0.1-SNAPSHOT.jar"]
# CMD ["./gradlew", "bootRun"]